import { CalendarDays, Plus, Search, Trophy, MoreHorizontal, Trash2, X, CheckCircle2 } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { matchesApi, type Innings, type Match } from "../api/cricpulse";
import { useAuth } from "../context/AuthContext";
export default function Matches(){const{user,isAuthenticated}=useAuth();const[matches,setMatches]=useState<Match[]>([]);const[toast,setToast]=useState("");const[scores,setScores]=useState<Record<number,Innings[]>>({});const[q,setQ]=useState("");const[filter,setFilter]=useState("ALL");useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(""),3600);return()=>window.clearTimeout(t)},[toast]);useEffect(()=>{matchesApi.list().then(async ms=>{setMatches(ms);const live=ms.filter(m=>m.status==="LIVE");const rows=await Promise.all(live.map(async m=>[m.id,await matchesApi.innings(m.id).catch(()=>[])] as const));setScores(Object.fromEntries(rows));}).catch(()=>setMatches([]))},[]);const shown=useMemo(()=>matches.filter(m=>filter==="ALL"||m.status===filter).filter(m=>`${m.team_a.name} ${m.team_b.name}`.toLowerCase().includes(q.toLowerCase())),[matches,filter,q]);return <main className="directory-page"><div className="directory-container"><section className="directory-hero matches-hero"><div className="directory-hero-copy"><span className="directory-kicker"><CalendarDays size={14}/> MATCH CENTRE</span><h1>Every match.<br/><span>One place.</span></h1><p>Live scores, upcoming fixtures and completed scorecards — all in one compact cricket hub.</p><div className="directory-actions">{isAuthenticated&&<Link to="/matches/create" className="directory-primary"><Plus size={17}/>Create a match</Link>}<div className="directory-proof"><Trophy size={16}/><span>{matches.length} matches in CricPulse</span></div></div></div><div className="match-hero-score"><span>CRICPULSE</span><strong>LIVE</strong><small>BALL BY BALL</small></div></section><section className="directory-search-card"><div><span className="directory-kicker">MATCH DIRECTORY</span><h2>Browse matches</h2></div><div className="directory-search-form"><div className="directory-search-input"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search teams…"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All matches</option><option value="LIVE">Live</option><option value="CREATED">Upcoming</option><option value="COMPLETED">Completed</option></select></div></section><section className="match-directory-grid">{shown.map(m=><MatchDirectoryCard key={m.id} match={m} innings={scores[m.id]||[]} canDelete={!!user && Number(user.id)===Number(m.creator_id)} onDelete={id=>{setMatches(v=>v.filter(x=>x.id!==id));setToast("Match deleted successfully")}}/>)}</section>{shown.length===0&&<div className="directory-empty"><CalendarDays size={38}/><h3>No matches found</h3><p>Try a different search or create a new match.</p></div>}</div>{toast&&<div className="cp-toast" role="status"><CheckCircle2 size={17}/><span>{toast}</span><button type="button" onClick={()=>setToast("")} aria-label="Close notification"><X size={15}/></button></div>}</main>}
function MatchDirectoryCard({match,innings,canDelete,onDelete}:{match:Match;innings:Innings[];canDelete:boolean;onDelete:(id:number)=>void}){
  const live=match.status==="LIVE";
  const current=innings.find(i=>i.status==="LIVE")||innings.at(-1);
  const [open,setOpen]=useState(false);
  const [deleting,setDeleting]=useState(false);
  const [message,setMessage]=useState("");
  async function del(){
    if(deleting)return;
    setDeleting(true);setMessage("");
    try{await matchesApi.delete(match.id);onDelete(match.id);setOpen(false)}
    catch(e){setMessage(e instanceof Error?e.message:"Unable to delete match.")}
    finally{setDeleting(false)}
  }
  return <article className={`match-directory-card ${live?"is-live":""}`}>
    <div className="match-directory-top">
      <span className={live?"home-live-pill":"match-status-pill"}>{live&&<span className="home-live-dot"/>}{live?"LIVE":match.status.replace("_"," ")}</span>
      {canDelete&&<div className="match-card-menu"><button type="button" className="match-card-menu-button" aria-label="More match options" aria-expanded={open} onClick={()=>{setOpen(v=>!v);setMessage("")}}><MoreHorizontal size={18} strokeWidth={2.4}/></button>{open&&<div className="match-card-menu-popover" role="menu"><div className="match-card-menu-title">Match options</div><button type="button" className="match-card-delete" onClick={del} disabled={deleting}><Trash2 size={15}/>{deleting?"Deleting…":"Delete match"}</button><button type="button" className="match-card-cancel" onClick={()=>setOpen(false)} disabled={deleting}>Cancel</button>{message&&<div className="match-card-delete-error"><X size={13}/>{message}</div>}</div>}</div>}
    </div>
    <Link to={`/matches/${match.id}`}><div className="match-directory-teams"><div><small>{match.team_a.short_name}</small><strong>{match.team_a.name}</strong>{innings.find(i=>i.batting_team.id===match.team_a.id)&&<b>{innings.find(i=>i.batting_team.id===match.team_a.id)?.runs}/{innings.find(i=>i.batting_team.id===match.team_a.id)?.wickets}</b>}</div><span>VS</span><div><small>{match.team_b.short_name}</small><strong>{match.team_b.name}</strong>{innings.find(i=>i.batting_team.id===match.team_b.id)&&<b>{innings.find(i=>i.batting_team.id===match.team_b.id)?.runs}/{innings.find(i=>i.batting_team.id===match.team_b.id)?.wickets}</b>}</div></div><div className="match-directory-foot"><span>{current?`${current.overs} ov`:format(match)}</span><span>{match.venue||match.location||"Venue TBC"}</span></div>{live&&current&&innings.length>1&&<div className="match-chase-line">{Math.max(0,innings[0].runs+1-current.runs)} needed · {Math.max(0,(match.overs||0)*6-current.legal_balls)} balls</div>}</Link>{match.status==="COMPLETED"&&<div className="match-completed">Completed match · open scorecard</div>}
  </article>
}

function format(m:Match){return m.format==="CUSTOM"?`Custom · ${m.overs} overs`:m.format}
